language: java

notifications:
 email: false

addons:
  sonarcloud:
    organization: "michelablack"
    token:
       secure: "XctyuzPp46IBddktE6MPLqcls/keNwQqfwUtnaBUqM6l1J8cQQI08jIkblY0I/CmdVsJAEojP/v3BllcS3SKleWeYye2pnFhTZKMJT0PBhZ3Hyxokmmxm3bFi3Z8eao9cS/+QWxkkYlrT1kuGlP8/W6Te0MA72nhy/LLhDuzBF/0qXpmQeieXmTkEdI8sDQa+bH6Hd2xBEKBoCsAsi+qF2knRCbZt+JeFw4cIDnP29x+qiIoH3HfPtt46MzOnYBrC96/1OwCrQwjOjTz3sAWNmEHmCqFK1ygPm96RCw7iqkIZLNVD9WLuU4caC38koL3Cw4FEpAfRhV7W1cZMxs1Ph5xUnRh1419Oinjjq+DFjHcfMDmFXl7jJESM4Hp7uC6vUc6LNSt8iUjwp81a9aFWmqkR4m/5BK7uIQhrag2ZDa8k02gHqyWwCopEc9YTfki8tFIPO8zspgTJgu3u/MnlBLG4rD3PfmESmtEBGKR5detLjUvzEQP0kn/cOroTfY/MIJGwaVWqSAf+XJ9+B70uScJDs6itg4TAsfAUj8s82OsNdRaRWCKyGsWMNPlqWSDaQAr+wx3Dsg62nHB4yH4qpA1xca85DzlLUDqyADSKOj7v+8LCZ0MaizXiWHUC1ATp0Br2ge2o9m3qcZ72kQK2tOxzH8+liJSk4aXZNITZDc=" 

script:  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install jacoco:prepare-agent jacoco:report -Dsonar.projectKey=michelablack_zookeeper-isw2
