language: java

notifications:
 email: false

addons:
  sonarcloud:
    organization: "michelablack"
    token:
       secure: "XIlRwGR9Z4sNQ1AnM5B1/QPl9vf6RCymI7EgSZI6aGyCQSOJJ5oBLO3Mv1rYFYuppHSUP+RfuXwr9a6grfXYMcH8sjEMqENqEo4LoL7sOsNjq3sCwNZUqEFi5CqkLhbkJQtC6t91ekzEHOMWo4pAcYznzLBowmr7kEAdAwVon87uJmMKcOJiTquqYrhZbMpnjakp97V5n/XnRxsVCsEmUjU3zJdVKhfXPcifgRJLOybFj47LzKU7xJVw3c7teozfdWTF4iFHg7fNA5G61hJY3qgv85R9siDee79hh5nKcinxunAusF2N4fv9/zzB0qQ40bEE8hai/rI23U1UFcjAg1HomoQ00StlVg8UT1LC3pNU6LdQJY42SCu9eVZYU06u7galuIahYN15+SXra1QLmAbU9GSrLix9cUEiS+9diYD/Xn5DpUcF+9+fAQ5DbjagNjCtlQNygdtRtpD34UK7f8nTeo8ys1G8x3NwDy1l+zna61EsAwduwyjWVYOkqyzqdPhMUoaQ3w8LJqMA47spiCWeSphW6xa077YqzjaxxlikF1yuavDaLcFBkNhFe9dNXqIYmTgZGaAXeL1hUrDUslsdfk23ZCVJviiXQl3pM84sO6inSPoVttnjdWgZFDWoKVuL4nDgPRSHUJ+EyzGH1kyaUPucNCWYrxcrf+PBnSs=" 

script:  
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
